# DataFrame
- Series가 1차원이어싿면 DataFrame은 2차원으로 확대된 버전이다.
- Excel의 SpreadSheet라고 생각하면 이해하기 쉽다.
- 2차원 이기 때문에 인덱스가 row, column으로 구성되어 있다.
    - row: 각 개별 데이터
    - column: 각 개별의 속성을 의미
- Data Analysis, Machine Learning 에서 Data를 변경하기 위해서 많이 사용된다.

[타이타닉 데이터 셋](https://drive.google.com/file/d/1QC5L7QEnweLQiqizWg7SldLeKoAa8Tme/view?usp=sharing)

In [118]:
import os
import numpy as np
import pandas as pd

base_path = r'C:\kdt_0900_pjh\data_analysis\resource\dataset'
file_name = r'titanic.csv'

file_path = os.path.join(base_path, file_name)

pd.read_csv(file_path).head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## 컬럼의 의미
    - survival: Survival(0 = no; 1 = yes)
    - class: Passenger Class(1 = 1st, 2 = 2nd, 3 = 3rd)
    - name: Name #이름
    - sex: Sex #성별
    - age: Age #나이
    - sibsp: Number of Siblings/Spouses Aboard #동승 형제
    - parch: Number of Parents/Children Aboard #동승 부모,자식
    - ticket: Ticket Number #티켓 번호
    - fare: Passenger Fare
    - cabin: Cabin # 객실번호
    - embarked - Pork of Embarkation(C = Cherbourg; Q = Queenstown, S = Southampthon) # 탑승장소

# 1. 데이터 파악
- shape: 속성(row, column)
- describe: 통계치 계산 함수(기술 통계량)
- info: 데이터의 타입, 각 컬럼의 개수 출력

In [119]:
tatanic_df = pd.read_csv(file_path)
print(tatanic_df.shape)

(891, 12)

In [20]:
print(tatanic_df.describe()) # 숫자로 된 데이터의 통계량만 볼 수 있다.

       PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008
std     257.353842    0.486592    0.836071   14.526497    1.102743
min       1.000000    0.000000    1.000000    0.420000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000
50%     446.000000    0.000000    3.000000   28.000000    0.000000
75%     668.500000    1.000000    3.000000   38.000000    1.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000

            Parch        Fare
count  891.000000  891.000000
mean     0.381594   32.204208
std      0.806057   49.693429
min      0.000000    0.000000
25%      0.000000    7.910400
50%      0.000000   14.454200
75%      0.000000   31.000000
max      6.000000  512.329200

In [25]:
print(tatanic_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None

In [28]:
print(tatanic_df.index)
print(tatanic_df.index.values)

RangeIndex(start=0, stop=891, step=1)
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395
 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413
 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431
 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449
 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467
 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485
 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503
 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521
 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539
 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557
 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575
 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593
 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611
 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629
 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647
 648 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665
 666 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683
 684 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701
 702 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719
 720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737
 738 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755
 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773
 774 775 776 777 778 779 780 781 782 783 784 785 786 787 788 789 790 791
 792 793 794 795 796 797 798 799 800 801 802 803 804 805 806 807 808 809
 810 811 812 813 814 815 816 817 818 819 820 821 822 823 824 825 826 827
 828 829 830 831 832 833 834 835 836 837 838 839 840 841 842 843 844 845
 846 847 848 849 850 851 852 853 854 855 856 857 858 859 860 861 862 863
 864 865 866 867 868 869 870 871 872 873 874 875 876 877 878 879 880 881
 882 883 884 885 886 887 888 889 890]

In [29]:
print(tatanic_df.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [31]:
len(tatanic_df)

891

In [32]:
print(tatanic_df.size)

10692

In [33]:
print(tatanic_df.ndim)

2

In [35]:
print(tatanic_df["Name"])
print(type(tatanic_df["Name"]))

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object
<class 'pandas.core.series.Series'>

## dict -> DataFrame

In [41]:
data = {"이름": "홍길동", "나이": 20, "주소": "서울시 강남"}

# dict 2차원인 incdex 값을 같이 제공해야한다.
pd.DataFrame(data, index=[i for i in range(3)])

    이름  나이      주소
0  홍길동  20  서울시 강남
1  홍길동  20  서울시 강남
2  홍길동  20  서울시 강남

In [43]:
data = {"이름": ["홍길동", "장보고", "이순신"], "나이": [20, 30, 40], "주소": ["서울시 강남구", "서울시 종로구", "서울시 관악구"]}
pd.DataFrame(data, index=[i for i in range(3)])

    이름  나이       주소
0  홍길동  20  서울시 강남구
1  장보고  30  서울시 종로구
2  이순신  40  서울시 관악구

In [47]:
a = pd.Series(data=["홍길동", 20, "경기도 수원"], index=["이름", "나이", "주소"])
b = pd.Series(data=["장보고", 30, "경기도 분당"], index=["이름", "나이", "주소"])
c = pd.Series(data=["이순신", 40, "경기도 의정"], index=["이름", "나이", "주소"])

pd.DataFrame([a, b, c])

    이름  나이      주소
0  홍길동  20  경기도 수원
1  장보고  30  경기도 분당
2  이순신  40  경기도 의정

## 데이터 프레임의 인덱싱

In [48]:
tatanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [53]:
# 데이터 프레임으로 슬라이싱
# 복수 컬럼을 가지고 올 수 있음

tatanic_df[["Name"]]
tatanic_df[["Name", "Age"]]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

## DataFrame 행 슬라이싱

In [56]:
tatanic_df[0:3]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [57]:
tatanic_df[::10].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,PC 17601,27.7208,NaN,C
40,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.0,1,0,7546,9.4750,NaN,S

## loc, iloc: row 선택

In [58]:
tatanic_df.loc[3]

PassengerId                                               4
Survived                                                  1
Pclass                                                    1
Name           Futrelle, Mrs. Jacques Heath (Lily May Peel)
Sex                                                  female
Age                                                    35.0
SibSp                                                     1
Parch                                                     0
Ticket                                               113803
Fare                                                   53.1
Cabin                                                  C123
Embarked                                                  S
Name: 3, dtype: object

In [59]:
tatanic_df.iloc[3]

PassengerId                                               4
Survived                                                  1
Pclass                                                    1
Name           Futrelle, Mrs. Jacques Heath (Lily May Peel)
Sex                                                  female
Age                                                    35.0
SibSp                                                     1
Parch                                                     0
Ticket                                               113803
Fare                                                   53.1
Cabin                                                  C123
Embarked                                                  S
Name: 3, dtype: object

In [61]:
# loc: 인덱싱을 해서 값이 띄엄띄엄 출력된 경우 고유 번호로만 조회가 가능
# iloc: 띄엄띄엄 출력된 값들도 순서대로 0, 1, 2, ..., 순서를 지정할 수 있다. 
tatanic_df[::10].iloc[1]

PassengerId                                 11
Survived                                     1
Pclass                                       3
Name           Sandstrom, Miss. Marguerite Rut
Sex                                     female
Age                                        4.0
SibSp                                        1
Parch                                        1
Ticket                                 PP 9549
Fare                                      16.7
Cabin                                       G6
Embarked                                     S
Name: 10, dtype: object

## 다중 행 데이터

In [62]:
tatanic_df.loc[[1, 600, 800]]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
600,601,1,2,"Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...",female,24.0,2,1,243847,27.0000,NaN,S
800,801,0,2,"Ponesell, Mr. Martin",male,34.0,0,0,250647,13.0000,NaN,S

In [63]:
tatanic_df[:3]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [64]:
tatanic_df.loc[:3]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [65]:
tatanic_df.loc[1]["Name"]
tatanic_df.loc[1, "Name"]

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [66]:
tatanic_df.iloc[-1]

PassengerId                    891
Survived                         0
Pclass                           3
Name           Dooley, Mr. Patrick
Sex                           male
Age                           32.0
SibSp                            0
Parch                            0
Ticket                      370376
Fare                          7.75
Cabin                          NaN
Embarked                         Q
Name: 890, dtype: object

In [70]:
print(tatanic_df[::5].loc[100, "Age"])

28.0

In [72]:
print(tatanic_df[::5].iloc[100], ["Age"])

PassengerId                 501
Survived                      0
Pclass                        3
Name           Calic, Mr. Petar
Sex                        male
Age                        17.0
SibSp                         0
Parch                         0
Ticket                   315086
Fare                     8.6625
Cabin                       NaN
Embarked                      S
Name: 500, dtype: object ['Age']

In [73]:
print(tatanic_df.loc[[100, 200, 300], ["Name", "Age"]])

                                         Name   Age
100                   Petranec, Miss. Matilda  28.0
200            Vande Walle, Mr. Nestor Cyriel  28.0
300  Kelly, Miss. Anna Katherine "Annie Kate"   NaN

In [76]:
print(tatanic_df.loc[[100, 200, 300]][["Name", "Age"]])

                                         Name   Age
100                   Petranec, Miss. Matilda  28.0
200            Vande Walle, Mr. Nestor Cyriel  28.0
300  Kelly, Miss. Anna Katherine "Annie Kate"   NaN

## Boolean Selection

In [85]:
age_mask = tatanic_df["Age"] >= 30
tatanic_df[age_mask]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [86]:
tatanic_df.Sex.value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [95]:
hogu_mask = tatanic_df["Fare"] >= 400
tatanic_df[hogu_mask]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C

In [123]:
## 여성의 생존자 조회
female_survived_mask = (tatanic_df["Survived"] == 1) & (tatanic_df["Sex"] == "female")
tatanic_df[female_survived_mask]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [178]:
# 1등석과 3등석의 생존율 비교
survived_mask = tatanic_df["Survived"] == 1
sur = len(tatanic_df[survived_mask])

pclass_first_mask = tatanic_df["Pclass"] == 1
first = len(tatanic_df[pclass_first_mask & survived_mask])

pclass_second_mask = tatanic_df["Pclass"] == 2
second = len(tatanic_df[pclass_second_mask & survived_mask])

pclass_third_mask = tatanic_df["Pclass"] == 3
third = len(tatanic_df[pclass_third_mask & survived_mask])

print(len(tatanic_df[survived_mask]))
print(f"1등석 생존자 수: {first}, 생존률: {round(first / sur, 2) * 100}%")
print(f"1등석 생존자 수: {second}, 생존률: {round(second / sur, 2) * 100}%")
print(f"3등석 생존자 수: {third}, 생존률: {round(third / sur, 2) * 100}%")

342
1등석 생존자 수: 136, 생존률: 40.0%
1등석 생존자 수: 87, 생존률: 25.0%
3등석 생존자 수: 119, 생존률: 35.0%

In [164]:
pclass_1_mask = tatanic_df["Pclass"] == 1
pclass_3_mask = tatanic_df["Pclass"] == 3

pclass_1_survived = len(tatanic_df[survived_mask & pclass_1_mask])
pclass_3_survived = len(tatanic_df[survived_mask & pclass_3_mask])

print(f"타이타닉호의 1등석 생존률: {pclass_1_survived / len(tatanic_df[pclass_1_mask]) * 100:.2f}%")
print(f"타이타닉호의 3등석 생존률: {pclass_3_survived / len(tatanic_df[pclass_3_mask]) * 100:.2f}%")

타이타닉호의 1등석 생존률: 62.96%
타이타닉호의 3등석 생존률: 24.24%

In [184]:
tatanic_df.groupby("Pclass")["Survived"].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [185]:
tatanic_df.groupby("Pclass")["Survived"].agg(["mean", "count"])

            mean  count
Pclass
1       0.629630    216
2       0.472826    184
3       0.242363    491

In [186]:
survived_pclass = tatanic_df.groupby("Pclass")["Survived"].mean()

pd.DataFrame(data=survived_pclass * 100, index=[1, 2, 3])

    Survived
1  62.962963
2  47.282609
3  24.236253

In [187]:
survived_pclass = tatanic_df.groupby("Pclass")["Survived"].mean()
survived_pclass.index = ["1등석", "2등석", "3등석"]
survived_pclass

pd.DataFrame(data=survived_pclass * 100, index=["1등석", "2등석", "3등석"])

      Survived
1등석  62.962963
2등석  47.282609
3등석  24.236253

# 파생 변수
- 기존에 존재하는 속성(변수, 컬럼)으로 부터 새로운 속성(컬럼)을 만들어낸 변수

In [179]:
tatanic_df["RealAge"] = tatanic_df["Age"] - 1

In [180]:
tatanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,RealAge
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,21.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,37.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,25.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,34.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,34.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,26.0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,18.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,25.0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,31.0

## 변수 삭제(Column 삭제): .drop()
- axis = 0(default) - 행 , 1 - 열
- inplace = False(default)

In [202]:
tatanic_df.drop('Cabin', axis = 1)

In [ ]:
titanic_df.drop(['Cabin','Embarked'], axis = 1)

In [ ]:
# btitanic_df.drop(['Cabin','Embarked'], axis = 1, inplace=True) 이거 하지말고 복사본 ㄱㄱ

## 파생 변수 만들기 연습

In [192]:
# 만약 NaN이라면: 알수없음
# 19세 이상: 성인
# 19세 미만: 아이
# if ~ elif ~ else
def get_adult(age):
    if np.isnan(age):
        return "알 수 없음"

    return "성인" if age >= 19 else "아이"

get_adult(18)

'아이'

In [204]:
# apply(): 앞의 시리즈의 값을 순차적으로 받아서 결과를 바꾸고 새로운 결과를 반환하는 함수
tatanic_df["IsAdult"] = tatanic_df["Age"].apply(get_adult)
tatanic_df

In [216]:
# RipOff
# Fare > 300: 바가지 요금
# Fare <= 300: 정상 요금

tatanic_df["RipOff"] = tatanic_df["Fare"].apply(lambda fare: "흑우" if fare > 300 else "정상")
tatanic_df[tatanic_df["Fare"] > 300]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,RealAge,IsAdult,RipOff
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C,34.0,성인,흑우
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,35.0,성인,흑우
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,34.0,성인,흑우